# This workflow searches for new versions of Mandelbulber2 and updates the repository

name: update

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install automatic updater
        run: Install-Module -Name AU -Force
        shell: pwsh

      - name: Run update script
        run: ./update.ps1
        shell: pwsh

      - name: Commit and push changes
        shell: pwsh
        run: |
          git config --global user.name 'Update Bot'
          git config --global user.email 'noreply@chocolatey.com'
          $changes = git status --porcelain
          if ($changes) {
            git commit -am "Automatic Update"
            git push
          } else {
            Write-Host "No changes to commit"
          }
